### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by lizhaojie001** [ohoachuck/wwdc-downloader#90]
![image](https://user-images.githubusercontent.com/14847521/59316452-37a3cf00-8cf1-11e9-9ee0-dcb0407fd547.png)
![image](https://user-images.githubusercontent.com/14847521/59316459-3f637380-8cf1-11e9-9cac-cdbd16887797.png)

xcode10.2.1

**Comment by ohoachuck** [comment]
Hello,
This is because you run the wwdcDownloader.swift. Due to a swift 5 bug (discussed with Apple at the lab), there is a crash that occur while running it through swift runtime. You have to run the wwdcDownloader.sh (bash script) which just compile the swift code just before running the compiled binary.
Alternatively you can do what does the bash script and create your binary for once (with swiftc).

O.

**Comment by ohoachuck** [comment]
Hello @lizhaojie001, does it work for you ?
Can I close this ?

O.

**Comment by lizhaojie001** [comment]
yes，you can . thank you


发自我的iPhone

------------------ Original ------------------

**Comment by ohoachuck** [comment]
Cool!
O.
